query IndexData {
  keyValuePairCollection(where: { key_in: ["Product name", "Tagline", "Studio URL"] }) {
    items {
      ...KeyValuePairData
    }
  }
  assetCollection(where: { title_in: ["Product logo", "Masthead demo image"] }) {
    items {
      ...IndexAssetData
    }
  }
}

fragment KeyValuePairData on KeyValuePair {
  key
  value
}

fragment IndexAssetData on Asset {
  title
  url
}
