query IndexData {
  keyValuePairCollection(where: {
    key_in: ["Product name", "Tagline"]
  }) {
    items {
      ...KeyValuePairData
    }
  }
  assetCollection(where: { title_in: ["Product logo"] }) {
    items {
      title
      url
    }
  }
  pageCollection(where: { id: "Index" }, limit: 1) {
    items {
      contentsCollection {
        items {
          ... on Content {
            ...ContentData
          }
          ... on Demo {
            ...DemoData
          }
          ... on Features {
            ...FeaturesData
          }
          ... on Masthead {
            ...MastheadData
          }
        }
      }
    }
  }
}

fragment KeyValuePairData on KeyValuePair {
  key
  value
}

fragment IconOrImageData on IconOrImage {
  image {
    url
  }
  chakraUiIconName
}

fragment ContentData on Content {
  heading
  contentDescription: description
  media {
    ...IconOrImageData
  }
}

fragment DemoData on Demo {
  heading
  url {
    value
  }
}

fragment FeaturesData on Features {
  heading
  featuresDescription: description
  featuresCollection(limit: 10) {
    items {
      heading
      description
      media {
        ...IconOrImageData
      }
    }
  }
}

fragment MastheadData on Masthead {
  heading
  subheading {
    value
  }
  image {
    url
  }
  ctaText {
    value
  }
  ctaLink {
    value
  }
  subtext
}
