query IndexData {
  keyValuePairCollection(where: {
    key_in: ["Product name", "Tagline"]
  }) {
    items {
      ...KeyValuePairData
    }
  }
  assetCollection(where: { title_in: ["Product logo", "Favicon"] }) {
    items {
      ...IndexAssetData
    }
  }
  pageCollection(where: { id: "Index" }, limit: 1) {
    items {
      contentsCollection {
        items {
          ... on Content {
            ...ContentData
          }
          ... on Demo {
            ...DemoData
          }
          ... on Features {
            ...FeaturesData
          }
          ... on Masthead {
            ...MastheadData
          }
          ... on Footer {
            ...FooterData
          }
        }
      }
    }
  }
}

fragment IndexAssetData on Asset {
  title,
  url
}

fragment KeyValuePairData on KeyValuePair {
  key
  value
}

fragment IconOrImageData on IconOrImage {
  image {
    url
  }
  faIconName
}

fragment ContentData on Content {
  heading
  contentDescription: description
  media {
    ...IconOrImageData
  }
  imageOnLeft
}

fragment DemoData on Demo {
  heading
  url {
    value
  }
}

fragment FeaturesData on Features {
  heading
  featuresDescription: description
  featuresCollection(limit: 10) {
    items {
      heading
      description
      media {
        ...IconOrImageData
      }
    }
  }
}

fragment MastheadData on Masthead {
  heading
  subheading {
    value
  }
  image {
    url
  }
  ctaText {
    value
  }
  ctaLink {
    value
  }
  subtext
}

fragment FooterData on Footer {
  organizationName {
    value
  }
  organizationIcon {
    url
  }
  iconsCollection(limit: 10) {
    items {
      url {
        value
      }
      icon {
        name
        collection
      }
    }
  }
  linksCollection(limit: 10) {
    items {
      text
      url {
        value
      }
    }
  }
}